trigger:
  branches:
    include:
      - main

variables:
  - group: FabricSecrets
  - name: AZURE_STORAGE_CONN
    value: $(STORAGE_CONN)
  - name: WORKSPACE_ID
    value: "b91bc81a-0c59-4fe4-ad98-be5f2f5c2716"

pool:
  vmImage: "ubuntu-latest"

steps:
  # 1️⃣ Use Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  # 2️⃣ Install Python dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  # 3️⃣ Verify Key Vault secrets are in environment
  - script: |
      echo "ClientID set: ${ClientID:+Yes}"
      echo "TenantID set: ${TenantID:+Yes}"
      echo "ClientSecret set: ${ClientSecret:+Yes}"  # do not print actual value
    displayName: 'Verify secrets are in environment'

  # 4️⃣ Run orchestrator
  - script: python scripts/orchestrator.py
    displayName: 'Deploy, run, and monitor pipelines'

  # Optional: Notify on failure
  - task: PowerShell@2
    displayName: "Notify on failure"
    condition: failed()
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "One or more pipelines failed. Check logs and Fabric workspace for details."
