trigger:
  branches:
    include:
      - main

variables:
  - group: FabricSecrets
  - name: AZURE_STORAGE_CONN
    value: $(STORAGE_CONN)
  - name: WORKSPACE_ID
    value: "b91bc81a-0c59-4fe4-ad98-be5f2f5c2716"

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install Python dependencies"

  # Orchestrator deploys, runs, and monitors both pipelines in order
  - script: |
      python scripts/orchestrator.py
    displayName: "Deploy, run, and monitor pipelines"

  # Optional: Notify on failure
  - task: PowerShell@2
    displayName: "Notify on failure"
    condition: failed()
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "One or more pipelines failed. Check logs and Fabric workspace for details."
